import type { ExerciseDef, DayDef, GromoData } from './types';

// The program, transcribed from the printed plan. This ships as the default
// data the first time the app runs; afterward localStorage is the source of truth.

const exercises: ExerciseDef[] = [
  // --- Upper Push ---
  {
    id: 'bench-press',
    name: 'Barbell Bench Press',
    kind: 'weighted-progress',
    sets: 4,
    repLow: 8,
    repHigh: 10,
    startWeight: 95,
    increment: 5,
    note: 'Anchor lift. Add 5 lbs the week you hit all reps cleanly. 2-3 sec descent, don\'t drop the bar.',
  },
  {
    id: 'cable-chest-press',
    name: 'Cable Chest Press',
    kind: 'weighted-progress',
    sets: 3,
    repLow: 10,
    repHigh: 12,
    startWeight: 30,
    increment: 5,
    note: 'Per side. Staggered stance, press forward and slightly down, squeeze at extension. Drop weight on the last set for burnout.',
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    kind: 'weighted-static',
    sets: 2,
    repLow: 12,
    repHigh: 15,
    startWeight: 20,
    note: 'Isolation, not a strength move. Wide arc, slight elbow bend, "hugging a tree." Skip if shoulder is fatigued.',
  },
  {
    id: 'cable-face-pull-push',
    name: 'Cable Face Pull (rope)',
    kind: 'weighted-static',
    sets: 3,
    repLow: 15,
    repHigh: 20,
    startWeight: 20,
    note: 'High, pull rope to forehead, elbows flare out. Never go heavy - burn in rear delts = correct weight.',
  },
  {
    id: 'db-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    kind: 'weighted-static',
    sets: 2,
    repLow: 15,
    repHigh: 15,
    startWeight: 10,
    note: '10-15 degrees forward (scapular plane). Lead with elbows, not hands.',
  },
  {
    id: 'rope-tricep-pushdown',
    name: 'Rope Tricep Pushdown',
    kind: 'weighted-progress',
    sets: 3,
    repLow: 12,
    repHigh: 15,
    startWeight: 35,
    increment: 5,
    note: 'Elbows pinned to sides. Push down and slightly outward at the bottom, fully extend the arm.',
  },
  {
    id: 'rope-tricep-burnout',
    name: 'Rope Tricep Pushdown (burnout)',
    kind: 'weighted-static',
    sets: 2,
    repLow: 15,
    repHigh: 20,
    startWeight: 20,
    note: 'Same exercise, drop weight significantly. Split rope apart at full extension for better contraction.',
  },

  // --- Lower Body ---
  {
    id: 'hyper-leg-extension',
    name: 'Hyper Pro Leg Extension',
    kind: 'weighted-progress',
    sets: 4,
    repLow: 12,
    repHigh: 15,
    startWeight: 25,
    increment: 5,
    note: 'Most important knee exercise. Slow tempo, 2 sec up / 3 sec down. Add weight only when you hit 15 reps with perfect tempo.',
  },
  {
    id: 'cable-tke',
    name: 'Cable TKE',
    kind: 'weighted-static',
    sets: 3,
    repLow: 15,
    repHigh: 20,
    startWeight: 5,
    note: 'Builds the teardrop muscle around the knee. Light, controlled.',
  },
  {
    id: 'hyper-hamstring-curl',
    name: 'Hyper Pro Hamstring Curl',
    kind: 'weighted-progress',
    sets: 3,
    repLow: 10,
    repHigh: 12,
    startWeight: 20,
    increment: 5,
    note: 'VMO isolation - knee strength. Start light, full ROM.',
  },
  {
    id: 'reverse-hyper',
    name: 'Reverse Hyper',
    kind: 'bodyweight',
    metric: 'reps',
    sets: 3,
    repLow: 12,
    repHigh: 15,
    note: 'Hips at edge, legs hanging. Raise to parallel, squeeze glutes at top, lower slowly. Good for L5-S1.',
  },
  {
    id: 'clamshell',
    name: 'Clamshell',
    kind: 'bodyweight',
    metric: 'reps',
    sets: 3,
    repLow: 15,
    repHigh: 20,
    note: 'Per side. Rotate top knee up, keep feet together. Band tightens it.',
  },
  {
    id: 'seated-calf-raise',
    name: 'Seated Dumbbell Calf Raise',
    kind: 'weighted-progress',
    sets: 3,
    repLow: 15,
    repHigh: 20,
    startWeight: 25,
    increment: 5,
    note: 'Ball of foot on edge step. Full range, bowl drops below step, all the way up on toes at top.',
  },
  {
    id: 'hyper-thrust',
    name: 'Hyper Thrust (rotate)',
    kind: 'bodyweight',
    metric: 'reps',
    sets: 3,
    repLow: 12,
    repHigh: 15,
    note: 'Pick 2 of the rotation each week. Upper back on pad, feet flat, drive hips to straight line.',
  },
  {
    id: 'hyper-back-extension',
    name: 'Hyper Pro Back Extension (rotate)',
    kind: 'bodyweight',
    metric: 'reps',
    sets: 3,
    repLow: 12,
    repHigh: 15,
    note: 'Pick 2 of the rotation each week. Hips at pad, lower back to neutral, squeeze glutes at top.',
  },
  {
    id: 'wall-squat',
    name: 'Stability Ball Wall Squat (rotate)',
    kind: 'bodyweight',
    metric: 'reps',
    sets: 3,
    repLow: 10,
    repHigh: 15,
    note: 'Pick 2 of the rotation each week. Ball behind back, lower to comfortable depth, only as deep as pain-free.',
  },

  // --- Core + Shoulder Maintenance ---
  {
    id: 'dead-bug',
    name: 'Stability Ball Dead Bug',
    kind: 'bodyweight',
    metric: 'reps',
    sets: 3,
    repLow: 8,
    repHigh: 10,
    note: 'Per side. Press ball into opposite hand and knee, extend other arm and leg.',
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    kind: 'bodyweight',
    metric: 'reps',
    sets: 3,
    repLow: 10,
    repHigh: 10,
    note: 'Per side. Opposite arm and leg, no shoulder rolling, hold 1 sec at top.',
  },
  {
    id: 'pallof-press',
    name: 'Pallof Press (cable)',
    kind: 'weighted-static',
    sets: 3,
    repLow: 12,
    repHigh: 12,
    startWeight: 10,
    note: 'Per side. Stand sideways, press straight out, hold, return. Resist the rotation.',
  },
  {
    id: 'ball-plank',
    name: 'Stability Ball Plank',
    kind: 'bodyweight',
    metric: 'time',
    sets: 3,
    repLow: 20,
    repHigh: 30,
    note: 'Forearms on ball instead of floor. Harder than regular plank - hips level, squeeze glutes.',
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    kind: 'bodyweight',
    metric: 'reps',
    sets: 3,
    repLow: 15,
    repHigh: 15,
    note: 'Feet flat, drive hips up, squeeze glutes at top, controlled down.',
  },
  {
    id: 'db-w-raise',
    name: 'Dumbbell W-Raise (prone)',
    kind: 'weighted-static',
    sets: 3,
    repLow: 12,
    repHigh: 15,
    startWeight: 5,
    note: 'Lie face down on incline bench. Raise arms into W shape, pull shoulder blades together. Light weight - this is for rotator cuff health.',
  },

  // --- Upper Pull ---
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    kind: 'weighted-progress',
    sets: 4,
    repLow: 8,
    repHigh: 12,
    startWeight: 95,
    increment: 5,
    note: 'Wide overhand grip. Full stretch at top before each rep. Pull to upper chest, not chin.',
  },
  {
    id: 'chest-supported-row',
    name: 'Chest-Supported Dumbbell Row',
    kind: 'weighted-progress',
    sets: 3,
    repLow: 10,
    repHigh: 12,
    startWeight: 25,
    increment: 5,
    note: 'Per hand. Lie face down on incline bench at 30-45 degrees. Row up toward hips, squeeze shoulder blades. Chest stays on bench - protects L5-S1.',
  },
  {
    id: 'db-shrugs',
    name: 'Dumbbell Shrugs',
    kind: 'weighted-progress',
    sets: 3,
    repLow: 12,
    repHigh: 15,
    startWeight: 45,
    increment: 5,
    note: 'Per hand. Straight up and down, no shoulder rolling. Hold 1 sec at top. Transition to barbell when you consistently hit 55-60 lbs each hand.',
  },
  {
    id: 'ez-bar-curl',
    name: 'EZ Bar Curl',
    kind: 'weighted-progress',
    sets: 3,
    repLow: 10,
    repHigh: 12,
    startWeight: 50,
    increment: 5,
    note: 'Total weight. Outer (wider) grip - easier on wrists and elbows. Full ROM, don\'t swing.',
  },
  {
    id: 'db-hammer-curl',
    name: 'Dumbbell Hammer Curl',
    kind: 'weighted-progress',
    sets: 2,
    repLow: 12,
    repHigh: 15,
    startWeight: 20,
    increment: 5,
    note: 'Neutral grip (palms facing each other). Hits brachialis - adds real arm thickness. Slow and controlled.',
  },
  {
    id: 'band-curl',
    name: 'Resistance Band Curl',
    kind: 'bodyweight',
    metric: 'reps',
    sets: 2,
    repLow: 15,
    repHigh: 20,
    note: 'Stand on band, curl up. Arms already pre-fatigued - burn them out with constant tension.',
  },
  {
    id: 'cable-face-pull-pull',
    name: 'Cable Face Pull (rope)',
    kind: 'weighted-static',
    sets: 3,
    repLow: 15,
    repHigh: 20,
    startWeight: 20,
    note: 'Both push and pull days, intentional. Single best thing for rotator cuff long term.',
  },
];

const days: DayDef[] = [
  {
    id: 'upper-push',
    name: 'Upper Push',
    subtitle: 'Chest · Shoulders · Triceps',
    exerciseIds: [
      'bench-press',
      'cable-chest-press',
      'cable-fly',
      'cable-face-pull-push',
      'db-lateral-raise',
      'rope-tricep-pushdown',
      'rope-tricep-burnout',
    ],
  },
  {
    id: 'lower-body',
    name: 'Lower Body',
    subtitle: 'Knee & back friendly',
    exerciseIds: [
      'hyper-leg-extension',
      'cable-tke',
      'hyper-hamstring-curl',
      'reverse-hyper',
      'clamshell',
      'seated-calf-raise',
      'hyper-thrust',
      'hyper-back-extension',
      'wall-squat',
    ],
  },
  {
    id: 'core-shoulder',
    name: 'Core + Shoulder',
    subtitle: 'No spinal flexion',
    exerciseIds: ['dead-bug', 'bird-dog', 'pallof-press', 'ball-plank', 'glute-bridge', 'db-w-raise'],
  },
  {
    id: 'upper-pull',
    name: 'Upper Pull',
    subtitle: 'Back · Biceps · Traps',
    exerciseIds: [
      'lat-pulldown',
      'chest-supported-row',
      'db-shrugs',
      'ez-bar-curl',
      'db-hammer-curl',
      'band-curl',
      'cable-face-pull-pull',
    ],
  },
];

export function buildSeed(): GromoData {
  const workingWeight: Record<string, number> = {};
  for (const ex of exercises) {
    if (ex.startWeight != null) workingWeight[ex.id] = ex.startWeight;
  }
  return { version: 1, days, exercises, logs: [], workingWeight };
}
